name: Publish to Maven Central
on:
  workflow_dispatch:
jobs:
  publish_to_maven_central:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_vicoSigningKey: ${{ secrets.VICO_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_vicoSigningPassword: ${{ secrets.VICO_SIGNING_PASSWORD }}
