name: Release update
on:
  workflow_dispatch:
jobs:
  release_update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Update README
        run: |
          OLD_VERSION_NAME=$(grep -oP "(?<=com\.patrykandpatryk\.vico:view:).*(?=\")" README.md)
          NEW_VERSION_NAME=$(grep -oP "(?<=version_name).*(?=\",)" versions.gradle | grep -oP "(?<=\").*")
          sed -i "s/$OLD_VERSION_NAME/$NEW_VERSION_NAME/g" README.md
          git config --global user.email "96002241+vicochartbot@users.noreply.github.com"
          git config --global user.name "Vico Chart Bot"
          git remote set-url origin https://vicochartbot:${{ secrets.VICO_CHART_BOT_PAT }}@github.com/patrykandpatryk/vico.git
          git add README.md
          git commit -m "Update README" -m "[skip ci]"
          git push origin
      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_vicoSigningKey: ${{ secrets.VICO_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_vicoSigningPassword: ${{ secrets.VICO_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_vicoUserName: ${{ secrets.VICO_USER_NAME }}
          ORG_GRADLE_PROJECT_vicoUserPassword: ${{ secrets.VICO_USER_PASSWORD }}
